
#hadoop-docker:
#  image: "sequenceiq/hadoop-docker:2.7.0"
#  hostname: hadoop-docker
#  name: hadoop-docker
#  command: /etc/bootstrap.sh -bash
#  ports:
#   - "8761:8761"

sequenceiq-spark:
  image: sequenceiq/spark:1.3.0
  hostname: sequenceiq-spark
  name: sequenceiq-spark
  command: bash